apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
      - name: cert-manager
        image: jetstackexperimental/cert-manager-controller:canary
        imagePullPolicy: Always
